load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "smol_di",
    hdrs = glob(["include/smol_di/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "smol_di_demo",
    srcs = ["SmolDi.cpp"],
    deps = [":smol_di"],
)
